import { Car } from "@/types";

export const cars: Car[] = [
  {
    id: "audi-a6-2024",
    name: "Audi A6",
    brand: "Audi",
    category: "Sedan",
    year: 2024,
    pricePerDay: 50000,
    seats: 5,
    luggage: 3,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "2.0L Turbo 4-Cylinder",
    horsepower: 261,
    topSpeed: "210 km/h",
    acceleration: "0-100 in 5.8s",
    features: [
      "Professional Driver",
      "Panoramic Sunroof",
      "Audi Virtual Cockpit",
      "Bang & Olufsen 3D Sound",
      "Matrix LED Headlights",
      "4-Zone Climate Control",
      "Wireless Apple CarPlay",
      "Leather Seats",
    ],
    images: ["/Images/Fleet/Audi_A6.jpeg"],
    color: "#FFFFFF",
    available: true,
    popular: true,
    description:
      "The Audi A6 combines sophistication with performance. Rent with a professional driver, fuel included, for travel all over Pakistan. Perfect for business executives and VIP travel.",
  },
  {
    id: "toyota-land-cruiser-prado",
    name: "Land Cruiser Prado",
    brand: "Toyota",
    category: "SUV",
    year: 2024,
    pricePerDay: 14000,
    seats: 7,
    luggage: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    engine: "2.8L Turbo Diesel",
    horsepower: 201,
    topSpeed: "165 km/h",
    acceleration: "0-100 in 11.5s",
    features: [
      "Professional Driver",
      "4WD with Multi-Terrain Select",
      "12.3 inch Touchscreen",
      "Toyota Safety Sense 3.0",
      "Adaptive Variable Suspension",
      "10 Speaker Audio System",
      "Wireless Apple CarPlay",
      "Hill Assist Control",
    ],
    images: ["/Images/Fleet/Land_Cruiser_Prado.jpeg"],
    color: "#FFFFFF",
    available: true,
    popular: true,
    description:
      "The Toyota Land Cruiser Prado is the ultimate travel companion. Comfortable, clean, and hassle-free — ready to be your travel solution. With driver, without fuel.",
  },
  {
    id: "toyota-land-cruiser-v8-zx",
    name: "Land Cruiser V8 ZX",
    brand: "Toyota",
    category: "SUV",
    year: 2024,
    pricePerDay: 24000,
    seats: 5,
    luggage: 6,
    transmission: "Automatic",
    fuel: "Diesel",
    engine: "3.3L V6 Twin-Turbo Diesel",
    horsepower: 309,
    topSpeed: "210 km/h",
    acceleration: "0-100 in 6.7s",
    features: [
      "Professional Driver",
      "3.3L V6 Twin-Turbo Engine",
      "10-Speed Automatic",
      "Crawl Control",
      "Kinetic Dynamic Suspension",
      "Premium Leather Interior",
      "14 Speaker JBL Audio",
      "Multi-Terrain Monitor",
    ],
    images: ["/Images/Fleet/Land_Cruiser_V8_ZX.jpeg"],
    color: "#FFFFFF",
    available: true,
    popular: true,
    description:
      "Experience the luxury of the Land Cruiser V8 ZX. The flagship SUV from Toyota delivers unmatched comfort and power for premium travel across Pakistan.",
  },
  {
    id: "mercedes-g63-amg",
    name: "Mercedes G63 AMG",
    brand: "Mercedes-Benz",
    category: "Luxury",
    year: 2024,
    pricePerDay: 110000,
    seats: 5,
    luggage: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L Twin-Turbo V8",
    horsepower: 577,
    topSpeed: "220 km/h",
    acceleration: "0-100 in 4.5s",
    features: [
      "Professional Driver",
      "AMG Performance V8 Biturbo",
      "Burmester Surround Sound",
      "AMG Sport Steering Wheel",
      "Designo Nappa Leather",
      "AMG Ride Control Suspension",
      "12.3 inch Dual Screens",
      "360 degree Camera",
    ],
    images: ["/Images/Fleet/Mercedes_G63_AMG.jpeg"],
    color: "#FFFFFF",
    available: true,
    popular: true,
    description:
      "The Mercedes G63 AMG is the ultimate statement of power and luxury. With driver, without fuel, available all over Pakistan for weddings, events, and VIP transport.",
  },
  {
    id: "mercedes-maybach-s-class",
    name: "Mercedes Maybach S-Class",
    brand: "Mercedes-Benz",
    category: "Luxury",
    year: 2024,
    pricePerDay: 110000,
    seats: 4,
    luggage: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.0L Twin-Turbo V8 EQ Boost",
    horsepower: 496,
    topSpeed: "250 km/h",
    acceleration: "0-100 in 4.8s",
    features: [
      "Professional Chauffeur",
      "4.0L V8 Biturbo with Mild Hybrid",
      "Burmester 4D Surround Sound",
      "First-Class Rear Executive Seats",
      "Magic Body Control Air Suspension",
      "MBUX Infotainment with AI",
      "Rear Seat Entertainment",
      "Executive Interior Lighting",
    ],
    images: ["/Images/Fleet/Mercedes_Maybach_S_Class.jpeg"],
    color: "#FFFFFF",
    available: true,
    popular: true,
    description:
      "The Mercedes-Maybach S-Class represents the pinnacle of automotive luxury. Experience first-class travel with professional chauffeur service all over Pakistan.",
  },
  {
    id: "range-rover-2024",
    name: "Range Rover",
    brand: "Land Rover",
    category: "Luxury",
    year: 2024,
    pricePerDay: 110000,
    seats: 5,
    luggage: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    engine: "4.4L Twin-Turbo V8",
    horsepower: 523,
    topSpeed: "250 km/h",
    acceleration: "0-100 in 4.6s",
    features: [
      "Professional Driver",
      "4.4L BMW Twin-Turbo V8",
      "Terrain Response 2 Auto",
      "Meridian Signature Sound",
      "Pixel LED Headlights",
      "Hot Stone Massage Seats",
      "Air Suspension with Wade Sensing",
      "13.1 inch Touchscreen",
    ],
    images: ["/Images/Fleet/Range_Rover.jpeg"],
    color: "#FFFFFF",
    available: true,
    popular: true,
    description:
      "The Range Rover combines British luxury with unmatched capability. Available with driver, without fuel, for premium travel across Pakistan's diverse terrain.",
  },
  {
    id: "toyota-hilux-revo",
    name: "Toyota Revo",
    brand: "Toyota",
    category: "SUV",
    year: 2024,
    pricePerDay: 12000,
    seats: 5,
    luggage: 3,
    transmission: "Automatic",
    fuel: "Diesel",
    engine: "2.8L Turbo Diesel (1GD-FTV)",
    horsepower: 201,
    topSpeed: "200 km/h",
    acceleration: "0-100 in 10.8s",
    features: [
      "Professional Driver",
      "4WD with Auto LSD",
      "8 inch Touchscreen Display",
      "Rear Parking Camera",
      "Hill Start Assist Control",
      "Traction Control System",
      "Bluetooth & USB Connectivity",
      "Cruise Control",
    ],
    images: ["/Images/Fleet/Toyota_Revo.jpeg"],
    color: "#FFFFFF",
    available: true,
    popular: true,
    description:
      "The Toyota Hilux Revo is built tough for any terrain. Ideal for northern areas adventure and off-road exploration in Pakistan. With driver, without fuel.",
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Ahmed Khan",
    avatar: "/images/avatars/avatar-1.jpg",
    rating: 5,
    comment:
      "Excellent service! Rented the Mercedes G63 AMG for my wedding. The car was immaculate and the service was professional. Highly recommended for special occasions.",
    date: "2024-06-15",
    carRented: "Mercedes G63 AMG",
  },
  {
    id: "2",
    name: "Fatima Ali",
    avatar: "/images/avatars/avatar-2.jpg",
    rating: 5,
    comment:
      "Took the Land Cruiser Prado for a trip to Hunza. The vehicle performed flawlessly on mountain roads. Will definitely rent again for my next adventure!",
    date: "2024-05-22",
    carRented: "Land Cruiser Prado",
  },
  {
    id: "3",
    name: "Usman Malik",
    avatar: "/images/avatars/avatar-3.jpg",
    rating: 5,
    comment:
      "Great experience renting the Audi A6 for a week. The car was clean, fuel-efficient, and perfect for city driving. The booking process was smooth.",
    date: "2024-07-01",
    carRented: "Audi A6",
  },
  {
    id: "4",
    name: "Sara Hussain",
    avatar: "/images/avatars/avatar-4.jpg",
    rating: 5,
    comment:
      "The Range Rover was perfect for our family trip to Murree. Spacious, comfortable, and the kids loved it. Apex Royale Drives made the whole process easy.",
    date: "2024-04-10",
    carRented: "Range Rover",
  },
  {
    id: "5",
    name: "Bilal Ahmed",
    avatar: "/images/avatars/avatar-5.jpg",
    rating: 5,
    comment:
      "Rented the Mercedes Maybach S-Class for a corporate event. My clients were impressed! The car is futuristic and the silent drive is amazing. Premium service.",
    date: "2024-06-28",
    carRented: "Mercedes Maybach S-Class",
  },
];

export const locations = [
  "Islamabad International Airport",
  "Blue Area, Islamabad",
  "F-8 Markaz, Islamabad",
  "G-9 Markaz, Islamabad",
  "Centaurus Mall, Islamabad",
  "Rawalpindi Saddar",
  "DHA Phase 5, Islamabad",
];
